apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: bc-db-credentials
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-1:493475752675:secret:dbcredentials-4hxj9E"
          objectVersion: "928a8779-1e9d-4a04-89f7-af701d620550"
          jmesPath: 
          - path: DATABASE_USER
            objectAlias: dbuser
          - path: DATABASE_PASSWORD
            objectAlias: dbpassword

---
