apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: bc-db-credentials
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "<your-secret-arn>"
          objectVersion: "<your-secret-version-ID>"
          jmesPath: 
          - path: DATABASE_USER
            objectAlias: dbuser
          - path: DATABASE_PASSWORD
            objectAlias: dbpassword

---
