name: Cloudsec-deployment-wf

on:
   workflow_dispatch:
   
permissions:
  checks: write

jobs:
  deploy:
        
    runs-on: ubuntu-latest
    #  needs: sast
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Load AWS EKS credentials
      run: aws eks update-kubeconfig --name cloudsec_cluster  --region us-east-1 # Change to your cluster name
    
    - name: Update Deployment Image 
      env:
            IMAGE_TAG_NODEJS: ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:nodejs-latest
            IMAGE_TAG_POSTGRES: ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:postgres-latest
            IMAGE_TAG_MAILCATCHER: ${{ vars.DOCKERHUB_USERNAME }}/brokencrystals:mailcatcher-latest
      run: |
            sed -i "s/IMAGE_NODEJS/$IMAGE_TAG_NODEJS/g" ./k8s/app.yaml
            sed -i "s/IMAGE_POSTGRES/$IMAGE_TAG_POSTGRES/g" ./k8s/app.yaml
            sed -i "s/IMAGE_MAILCATCHER/$IMAGE_TAG_MAILCATCHER/g" ./k8s/app.yaml

    - name: Deploy to EKS
      run: kubectl apply -f k8s/  --validate=false # Path to your Kubernetes config files
    
    - name: Verify deployment
      run: kubectl rollout status deployment/githubactions-demo  # Change to your deployment resource name



